DROP DATABASE IF EXISTS cookbookdb;

-- CREATE DATABASE
CREATE DATABASE cookbookdb;

-- CREATE TABLE books(
--   id INTEGER(11) AUTO_INCREMENT NOT NULL,
--   authorId INTEGER(11),
--   title VARCHAR(100),
--   PRIMARY KEY (id)
-- );

